apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
 name: mon-pdb
 namespace: rook-ceph
spec:
#A consensus requires a majority of monitors running to establish a quorum for consensus
#about the cluster map (e.g., 1; 2 out of 3; 3 out of 5; 4 out of 6; etc.)
 minAvailable: 2
 selector:
   matchLabels:
     app: rook-ceph-mon

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
 name: mds-pdb
 namespace: rook-ceph
spec:
 minAvailable: 1
 selector:
   matchLabels:
     app: rook-ceph-mds
